# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [4]:
%run initialise.py

ModuleNotFoundError: No module named 'mdutils'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [20]:
print("version : ",np.__version__)
print("__________________________\n")
print("configration : \n")
np.show_config()

version :  1.21.5
__________________________

configration : 

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/z-4444/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/z-4444/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/z-4444/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/z-4444/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/z-4444/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/z-4444/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/z-4444/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/z-4444/anaconda3/include']
Supported SIMD extensions in this NumPy i

#### 3. Create a null vector of size 10 (★☆☆)

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
arr = np.array([1,2,3,4,5,'er'])
print(arr.size)
print(arr.itemsize)

6
84


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
python -c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (2787590163.py, line 1)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
vac = np.zeros(10)
vac[6] = 1
print(vac)

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [20]:
print(np.flip(np.arange(1,5)))
print(np.arange(1,5)[::-1])
print(np.arange(1,5,-1))

[4 3 2 1]
[4 3 2 1]
[]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [25]:
np.eye(3 , dtype=int)
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [28]:
arr = np.array([1,2,0,0,4,0])
np.where(arr != 0)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [30]:
np.identity(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [63]:
arr1 = np.random.rand(3,3,3)
arr2 = np.random.random(27).reshape(3,3,3)
arr3 = np.random.randint(0, 27, (3, 3, 3))
if arr1.ndim == arr2.ndim == arr3.ndim:
    print("well done")

well done


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [66]:
arr = np.random.rand(10,10)
print("max value :",np.max(arr) ,"\n min value: ",np.min(arr))

max value : 0.9708544088977066 
 min value:  0.00737220844193176


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [68]:
np.mean(np.random.random(10))

0.43500794247680064

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [84]:
arr = np.ones((4,4))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [6]:
arr = np.ones((3,3))

np.pad(arr, pad_width = ((1,2),(3,1)) , mode = "constant", constant_values = 3)

# print(arr)

array([[3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 1., 1., 1., 3.],
       [3., 3., 3., 1., 1., 1., 3.],
       [3., 3., 3., 1., 1., 1., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [107]:
0* np.nan
print(np.inf)
print(np.nan == np.nan)
print(np.inf < np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
a = 0.3
b = 3*0.1
a==b
print("b : ",b)

inf
False
False
nan
True
b :  0.30000000000000004


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [14]:
# arr = np.ones((5,5))
# arr = np.arange(25).reshape(5,5)
# print(arr)
# print("==========================")
# dag = np.diag(arr, k= -1)
# print(dag)
# print("==========================")
# inx = np.where(np.diag(arr, k= -1))
# print(inx)
# print("==========================")

# print("before:",dag[inx])
# np.diag(dag, k=-1)
# print(np.diag([1,2,3]))
np.diag(1+np.arange(4),k=-1)


[[1 0 0]
 [0 2 0]
 [0 0 3]]


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [24]:
mat = np.ones((8,8))
mat[1::2, ::2] = 0
mat[::2, 1::2] = 0
mat

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [39]:
arr = np.arange(336).reshape(6,7,8)
print(arr.dtype)
arr[1,5,4]

int64


100

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [40]:
np.tile(np.identity((4)),(2,2))

array([[1., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 1.]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [52]:
arr = (np.random.rand(5,5)*25).astype(int)
s = np.sum(arr,axis=0)
z = np.divide(arr,s)*10
print(z)
z.max()

[[0.22727273 0.81632653 0.16129032 3.15789474 1.76470588]
 [0.45454545 2.24489796 3.87096774 2.36842105 2.64705882]
 [1.81818182 4.08163265 1.61290323 1.97368421 3.38235294]
 [5.22727273 1.83673469 1.12903226 1.18421053 1.17647059]
 [2.27272727 1.02040816 3.22580645 1.31578947 1.02941176]]


5.227272727272727

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [57]:
np.array([('r',np.ubyte),('g',np.ubyte),('b',np.ubyte),('a',np.ubyte)])
np.dtype([('r',np.ubyte),('g',np.ubyte),('b',np.ubyte),('a',np.ubyte)])

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [58]:
a = (np.random.rand(5,3)*100).astype(int)
b = (np.random.rand(3,2)*100).astype(int)
np.dot(a,b)

array([[5541, 2376],
       [4500, 1131],
       [6452, 2915],
       [5713, 1885],
       [6716, 1673]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [3]:
arr = (np.random.rand(10)*10).astype(int)
print("before filter : ", arr)
# indx = np.where((arr>3) & (arr<8),arr,-1*arr)
# indx = np.where((arr>3) & (arr<8))
mask = (arr>3) & (arr<8)
print(mask)
arr[mask] *= -1
print("after filter : ", arr)

# print(arr[indx] * -1)


before filter :  [4 4 2 2 1 0 3 7 0 2]
[ True  True False False False False False  True False False]
before filter :  [-4 -4  2  2  1  0  3 -7  0  2]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [91]:
print(sum(range(5)))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [101]:
Z = np.array(range(5))
Z, Z*Z,  2 << Z >> 2,  Z <- Z, 1j*Z, Z/1/1
# Z<Z>Z # not valid operator raise an error

(array([0, 1, 2, 3, 4]),
 array([ 0,  1,  4,  9, 16]),
 array([0, 1, 2, 4, 8]),
 array([False, False, False, False, False]),
 array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j]),
 array([0., 1., 2., 3., 4.]))

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [105]:
# np.array(0) / np.array(0)
# np.array(0) // np.array(0)
nn = np.array([np.nan]).astype(int).astype(float)
print(nn)

[-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆)

In [111]:
arr = np.random.uniform(-2,10,10)
print("arr: ",arr)
print("========================================\n\n")
print("round: ",np.round(arr))
print("=======================================\n\n")
print("ceil: ",np.ceil(arr))
print("=======================================\n\n")
print("floor: ",np.floor(arr))
print("======================================\n\n")
print("copysign: ",np.copysign(arr,-1))
print("======================================\n\n")
print("abs: ",np.abs(arr))
print("======================================\n\n")

arr:  [ 8.27739062  2.04380685 -0.17541213  4.43812324  8.38100949 -0.26396276
 -0.6918522   9.18035632  6.00900342  2.14071313]


round:  [ 8.  2. -0.  4.  8. -0. -1.  9.  6.  2.]


ceil:  [ 9.  3. -0.  5.  9. -0. -0. 10.  7.  3.]


floor:  [ 8.  2. -1.  4.  8. -1. -1.  9.  6.  2.]


copysign:  [-8.27739062 -2.04380685 -0.17541213 -4.43812324 -8.38100949 -0.26396276
 -0.6918522  -9.18035632 -6.00900342 -2.14071313]


abs:  [8.27739062 2.04380685 0.17541213 4.43812324 8.38100949 0.26396276
 0.6918522  9.18035632 6.00900342 2.14071313]




#### 30. How to find common values between two arrays? (★☆☆)

In [3]:
arr1 = np.random.uniform(1,15,10).astype(int)
arr2 = np.random.uniform(1,20,10).astype(int)
np.intersect1d(arr1,arr2)

array([2, 3, 6, 7])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [4]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
#no

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [10]:
today = np.datetime64('today',"D")
yesterday = np.datetime64('today',"D") - np.timedelta64('1',"D")
tomorrow = np.datetime64('today',"D") + np.timedelta64('1',"D")
print("today: \t",today,"\n yesterday: \t",yesterday,"\n tomorrow: \t",tomorrow)

today: 	 2023-02-20 
 yesterday: 	 2023-02-19 
 tomorrow: 	 2023-02-21


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [21]:
year, month = 2016, 7
days = np.datetime64(f"{year}-0{month+1}-01")- np.datetime64(f"{year}-0{month}-01")
dates = np.arange(f'{year}-0{month}-01', f'{year}-{month+1}-01', dtype='datetime64')
print(dates)
# dates = np.arange(f'{year}-0{month}-01', f'{year}-0{month+1}-01', dtype='datetime64')

# # Print the dates
# print(dates)
# # np.arange(np.timedelta64(dates,dtype="datetime64"))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [7]:
A = np.array([1,2,3])
B = np.array([4,5,6])

np.multiply(sum(A,B),(np.divide(np.negative(A),2)))

array([ -5., -11., -18.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
# np.ceil, np.floor, astype(int), np.round

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [10]:
np.tile((np.arange(5)),5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [17]:
def generator():
    for i in range(10):
        yield i
np_array = np.array(list(generator()))
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)