In [2]:
import numpy as np
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [2]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])


In [3]:
arr2 = np.array([[1,1,1],[2,2,2]])
arr2.ndim

2

In [4]:
arr3 = np.array([[[1,1,1],[2,2,2]],[[3,3,1100],[4,4,4]]])
print(arr3.ndim)
arr3[1,0,2]

3


1100

In [5]:
arr4 = np.array([[[[1,1,1],[2,2,2]],[[3,3,1100],[4,4,4]]],[[[1,1,1],[2,2,2]],[[3,3,10101],[4,4,4]]]])
print(arr4.ndim)
arr4[1,1,0,2]

4


10101

In [6]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
new = arr[0, 1]
s_new = arr[0:2,1:2]
print('s:',s_new)
print('type of  s_new : ',type(s_new))
print(new)
print(type(new))

s: [[2]
 [7]]
type of  s_new :  <class 'numpy.ndarray'>
2
<class 'numpy.int64'>


In [16]:
l1 = ["eat", "sleep", "repeat"]
s1 = "geek"
  
# creating enumerate objects
obj1 = enumerate(l1)
obj2 = enumerate(s1)
  
print ("Return type:", type(obj1))
print ("list 1 :",list(enumerate(l1)))
  
# changing start index to 2 from 0
print (list(enumerate(s1)))

print({ k : v for k, v in enumerate(s1) })

Return type: <class 'enumerate'>
list 1 : [(0, 'eat'), (1, 'sleep'), (2, 'repeat')]
[(0, 'g'), (1, 'e'), (2, 'e'), (3, 'k')]
{0: 'g', 1: 'e', 2: 'e', 3: 'k'}


In [21]:
a = ([1,2,3], [4,5,6])
b = np.empty_like(a)
print("array :",b ,"datatype : ", b.ndim)

array : [[1 2 3]
 [4 5 6]] datatype :  2


In [25]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)
print("as",np.arange(4))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
as [0 1 2 3]


In [2]:
# array([0, 1, 2, 3])
np.diag([[1, 2, 3],[4,5,6]],k=-1)
# np.arange(4)

array([4])

In [10]:
arr = np.array([1,2,3])
np.tile(arr,(3,3,2))

array([[[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]],

       [[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]],

       [[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]]])

In [13]:
from PIL import Image

# Load image as RGBA
img = Image.open('/home/z-4444/DS_trainning/day4/im.png').convert('RGBA')

# Convert to NumPy array
img_array = np.array(img)
print(img_array)

[[[ 20  20  20 255]
  [ 20  20  20 255]
  [ 20  20  20 255]
  ...
  [193 193 193 255]
  [241 241 241 255]
  [241 241 241 255]]

 [[ 20  20  20 255]
  [ 20  20  20 255]
  [ 20  20  20 255]
  ...
  [193 193 193 255]
  [241 241 241 255]
  [241 241 241 255]]

 [[ 20  20  20 255]
  [ 20  20  20 255]
  [ 20  20  20 255]
  ...
  [193 193 193 255]
  [241 241 241 255]
  [241 241 241 255]]

 ...

 [[ 20  20  20 255]
  [ 20  20  20 255]
  [ 20  20  20 255]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[ 20  20  20 255]
  [ 20  20  20 255]
  [ 20  20  20 255]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[ 20  20  20 255]
  [ 20  20  20 255]
  [ 20  20  20 255]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]]


In [17]:
arr = np.array([1,2,4,3,5,6])
mask = (arr == 2) | (arr == 3)
print(mask)
arr[mask] *= -1
arr

[False  True False  True False False]


array([ 1, -2,  4, -3,  5,  6])

In [25]:
arr = (np.random.rand(10)*10).astype(int)
print(arr)
mask = (arr>3) & (arr<8)
print(mask)
arr[mask] *= -1
print(arr)

[2 9 0 0 5 6 5 8 6 2]
[False False False False  True  True  True False  True False]
[ 2  9  0  0 -5 -6 -5  8 -6  2]


In [32]:
arr = np.array([1,2.23,-1.23,-0.12])
np.floor(arr)

array([ 1.,  2., -2., -1.])

In [4]:
np.datetime64("July","M")

ValueError: Error parsing datetime string "July" at position 0